remote_theme: github-profile-achievements/jekyll-theme

title:  Liste complète de tous les badges et réalisations du profil GitHub 
description:  Liste complète de tous les badges et réalisations du profil GitHub 
permalinks: pretty

lang: fr
logo_url: https://avatars.githubusercontent.com/u/117988194?s=200&v=4

# Navbar
navbar_link_text: Réalisations du profil GitHub dans d'autres langues
navbar_button_text: Cette page sur GitHub
